language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      language: generic

env:
  global:
    - CIBW_BUILD='cp37-*'
    - CIBW_BEFORE_BUILD='pip install cmake'
    - CIBW_TEST_REQUIRES=nose
    - CIBW_TEST_COMMAND='nosetests {project}/python/pylibtermkey'
    - TWINE_USERNAME='michael.vilim'
    # encrypted TWINE_PASSWORD
    - secure: 'f3b7xQgoFFY92CL/3kcoj73CxwtofF54Y/rKqyhnBaIv9tpn/IyeuLlPc5TIhagSFCxSkVI66uA2M2sg8wv0npPS4y3lahOsrjPXUGvK6vDkD4gI6HvEIGmFMA+uVwaLhlQ71qdaBIVvWoKNMpIgzs0M9WIwoIPFn/hqPna4FCuxIJ94d+CNxAMOQ7oFxiB1WpCqMVce2EylKgm/xG1QNU1sfFj0OYeOF7E/A39ccHWYY8+niNwu+Fq17GrKOhp+BT4L62jhUai2ZzNunZaWuqxXAdAyjUhgbk89mZLIPsTAb4z3lNLLuvRiaKpKzrEXKkubpqU1IFKkyCMr5LJTUg98XuzSrpMC6r8Ld5ymiZiVBuQtKHZhd75c03T6wRB/rxU+ziLCs7HJWQahVjN+pFDJJjhqjZRehwTtTzU2i8OdckdwmScWRMb4T+2J51WKpKR89UIWPIYs3yDRf8nYcR5b6J4nsn1Xx6rCr4LH9DDhghfd978vP7rbb9h2G3TLGmLbNfxQ0PsAkJhQVN03SNiAM8qjB/CAbvjPdgplasi10NZKCZsUZ0nuXD7MHstQq0Q7qaurfna4NcYpw8Qqmqdxk+yr9JGsz5Ot8ANz7J9lsZJphQYWVywB9qxrSDEQybQL1SxaBcjOH24ioRfzoyprlcHg9DXQgXPEGDmptpM='

script:
  # temporary fix for https://github.com/joerick/cibuildwheel/issues/122
  # - pip install cibuildwheel==0.10.0
  - pip install git+https://github.com/YannickJadoul/cibuildwheel.git@pip-19-stalling-workaround
  - cibuildwheel --output-dir dist
  - python setup.py sdist --dist-dir dist

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true
