language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      language: generic

env:
  global:
    - CIBW_BUILD='cp37-*'
    - CIBW_BEFORE_BUILD='pip install cmake'
    - CIBW_TEST_REQUIRES=nose
    - CIBW_TEST_COMMAND='nosetests {project}/python/pylibtermkey'
    - TWINE_USERNAME='michael.vilim'
    # encrypted TWINE_PASSWORD
    - secure: 'LF9Gw/Pe1I6TiQo6tpL8CuZcQgbDycvx3Bgqnb52iOkYm4HtnEv5zgFeowKbxlJs/stxy3t851+Qj8QD1aRaQzI+sAZIc5qZiZNLWyHQ9+JA0NkDcs1up6zMMJtiYzI6rWLn1NHusOVDj8FSYXiZ4nvP0s033HRtxrBCItYCtwrVEQw55jQiNaLNo0Ix0nB+mOrL9k37xQX95CEov9tR+R2C/E+wYEHF6/EE0rxSnHBnORFEsDodj72wf9aeQQB74EFAXA7bvHf39MeS8ExaWl4tVcCMXQhfBkC2EFE57AN+JMSacufWE62H/PBpxDQU/zjdL1xPaFofEt+vgaJ7jUIPowWUtsYoegsV8XPxuENGFFxzY8PUGV69dzK4Jld6orK4VcdvTr3Ydra9PkLGEllrCj8C8sWosOQSpvSu569SBsN+I4kPJ1e6QHFBNmJUPP8zL2eP6EY/uj9sMKU89QmGGXTwjaf4Ws2CC6trR3ggupChbAL+K1fqqF1gYDB0vjNU8THaF22SCkR4AdXUZRrGD5njGMfKEOrl+5h/LIjcOZof/BkKzl/anfnLF957zpsh+hBYrn1AuXWr0eM3y0Fj+1Uq3jd2LWTx9jYJ2KTFmO2iCdCeW/s7axJjTq3PnEmZ4Lh+9xMMOhCf3BLeb+TQawYj24NkMoENH5cw03g='

script:
  # temporary fix for https://github.com/joerick/cibuildwheel/issues/122
  # - pip install cibuildwheel==0.10.0
  - pip install git+https://github.com/YannickJadoul/cibuildwheel.git@pip-19-stalling-workaround
  - cibuildwheel --output-dir dist
  - python setup.py sdist --dist-dir dist

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true
