language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      language: generic

env:
  global:
    - CIBW_BUILD='cp37-*'
    - CIBW_BEFORE_BUILD='pip install cmake'
    - CIBW_TEST_REQUIRES=nose
    - CIBW_TEST_COMMAND='nosetests {project}/python/pylibtermkey'
    - TWINE_USERNAME='michael.vilim'
    # encrypted TWINE_PASSWORD
    - secure: 'hGvEyxVrNoqFl59hqufZMcbeuLIKA4wmHjl57cO6HNkihmsyXaIXRMVX/yn1PIu/3iutMdFuuHALce4h3att8m/PfqpXe9wfvhaiqNDC5B4iMPLJB1KnetlTpimMZUbYvOY/PPIPB51/ayoLdbfs+ROSEbFBh7Y2gZWaMuUPGvcSYyCTz62FMOb1OCzkOKZZuIJmG8/DUnbjwA8NiIoCC3PLmAaGUxuyE1XsRxNIwyCRV5OVtgzmmnJBpvApxvIcHhBFWpx8mx+3e39KmGstubM0MbowBg9LooryYDf+TLMBjtTPG5F78fwTzyzd6ntC/tceJ93TnTuAlkXzmK8Yao9DHMusRQXHN7ZrcBLeVWborcEPp6IBvkyok+yaiXeiwZI86hbKdR1aF+6pN1mO1KdujE/eTe5Mf+kw6F6Z45RoeFOSf8tlw9pPQyIKXEor/JTBsJ1birxhRpUfojdOXD/l7T8OimkiwXkyyX2aGfrBNH/p6zDMnzVk0Uzu6UyBEwe/KBC2apMbEWr9NgdHV/3qT2hLBpU6C/bp2IZcISRTwXuqGDMeWaAh0fQPdgeIXLCVtFIG7Bx6gFeGoYPdkmLrYBZwzUHmOm+GZs4cakFLYBK5JtGyBmhiG4vh35+JOzcMmtDDnBVnF1RtvOyr8GBej3dlELQ8aX3Agi6V6Wg='

script:
  # temporary fix for https://github.com/joerick/cibuildwheel/issues/122
  # - pip install cibuildwheel==0.10.0
  - pip install git+https://github.com/YannickJadoul/cibuildwheel.git@pip-19-stalling-workaround
  - cibuildwheel --output-dir dist
  - python setup.py sdist --dist-dir dist

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true
