language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      language: generic

env:
  global:
    - CIBW_BUILD='cp37-*'
    - CIBW_BEFORE_BUILD='pip install cmake'
    - CIBW_TEST_REQUIRES=nose
    - CIBW_TEST_COMMAND='nosetests {project}/python/pylibtermkey'
    - TWINE_USERNAME='michael.vilim'
    # TWINE_PASSWORD is stored in the travis project settings

script:
  # temporary fix for https://github.com/joerick/cibuildwheel/issues/122
  # - pip install cibuildwheel==0.10.0
  - pip install git+https://github.com/YannickJadoul/cibuildwheel.git@pip-19-stalling-workaround
  - cibuildwheel --output-dir dist
  - python setup.py sdist --dist-dir dist

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true
