language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      language: generic

env:
  global:
    - CIBW_BUILD='cp37-*'
    - CIBW_BEFORE_BUILD='pip install cmake'
    - CIBW_TEST_REQUIRES=nose
    - CIBW_TEST_COMMAND='nosetests {project}/python/pylibtermkey'
    - TWINE_USERNAME='michael.vilim'
    # TWINE_PASSWORD is stored in the travis project settings

script:
  - bash scripts/build.sh

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    tags: true
