language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      language: generic

env:
  global:
    - CIBW_SKIP='cp27-* cp34-* cp38-* *-manylinux_i686'
    - CIBW_BEFORE_BUILD='./scripts/before_build.sh'
    - CIBW_TEST_REQUIRES=nose
    - CIBW_TEST_COMMAND='nosetests {project}/python/pylibtermkey'
    - CIBW_MANYLINUX_X86_64_IMAGE=manylinux2014
    - TWINE_USERNAME='mvilim'
    # TWINE_PASSWORD is stored in the travis project settings

script:
  - bash scripts/travis_build.sh

deploy:
  provider: script
  script: bash scripts/travis_deploy.sh
  skip_cleanup: true
  on:
    tags: true
